-- Migration: Create CNS Logs Table
-- Description: Separate table for CNS-specific tracking
-- Date: 2026-06-05

CREATE TABLE IF NOT EXISTS cns_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  cns_fatigue INTEGER NOT NULL DEFAULT 0 CHECK (cns_fatigue >= 0 AND cns_fatigue <= 100),
  grip_fatigue INTEGER NOT NULL DEFAULT 0 CHECK (grip_fatigue >= 0 AND grip_fatigue <= 100),
  isometric_strain INTEGER NOT NULL DEFAULT 0 CHECK (isometric_strain >= 0 AND isometric_strain <= 100),
  notes TEXT,
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_cns_logs_user ON cns_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_cns_logs_date ON cns_logs(log_date DESC);

-- Enable RLS
ALTER TABLE cns_logs ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view own CNS logs" ON cns_logs
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own CNS logs" ON cns_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own CNS logs" ON cns_logs
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own CNS logs" ON cns_logs
  FOR DELETE USING (auth.uid() = user_id);

-- Add comments
COMMENT ON TABLE cns_logs IS 'Central nervous system fatigue tracking for athletes';
COMMENT ON COLUMN cns_logs.cns_fatigue IS 'Central nervous system fatigue level (0-100)';
COMMENT ON COLUMN cns_logs.grip_fatigue IS 'Grip strength fatigue level (0-100)';
COMMENT ON COLUMN cns_logs.isometric_strain IS 'Isometric strain level (0-100)';
