-- Migration: Create Arm Wrestling Logs Table
-- Description: Separate table for arm wrestling specific metrics
-- Date: 2026-06-05

CREATE TABLE IF NOT EXISTS armwrestling_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  side_pressure_fatigue INTEGER NOT NULL DEFAULT 0 CHECK (side_pressure_fatigue >= 0 AND side_pressure_fatigue <= 100),
  forearm_recovery INTEGER NOT NULL DEFAULT 0 CHECK (forearm_recovery >= 0 AND forearm_recovery <= 100),
  training_load INTEGER NOT NULL DEFAULT 0 CHECK (training_load >= 0 AND training_load <= 100),
  match_notes TEXT,
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_armwrestling_logs_user ON armwrestling_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_armwrestling_logs_date ON armwrestling_logs(log_date DESC);

-- Enable RLS
ALTER TABLE armwrestling_logs ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view own arm wrestling logs" ON armwrestling_logs
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own arm wrestling logs" ON armwrestling_logs
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own arm wrestling logs" ON armwrestling_logs
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own arm wrestling logs" ON armwrestling_logs
  FOR DELETE USING (auth.uid() = user_id);

-- Add comments
COMMENT ON TABLE armwrestling_logs IS 'Arm wrestling specific recovery metrics';
COMMENT ON COLUMN armwrestling_logs.side_pressure_fatigue IS 'Side pressure fatigue level (0-100)';
COMMENT ON COLUMN armwrestling_logs.forearm_recovery IS 'Forearm recovery percentage (0-100)';
COMMENT ON COLUMN armwrestling_logs.training_load IS 'Training load intensity (0-100)';
